### ISSUE TITLE
General issue about ExpFactory categories that may not be pressing at this time

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#105]
The tasks in the expfactory website are categorized in strange ways (e.g., flanker is a "task difficulty" task).

**Comment by vsoch** [comment]
This is because of Cognitive Atlas assertions :) We probably don't want to venture down this road yet...

**Comment by bissettp** [comment]
I thought not, but I

**Comment by vsoch** [comment]
It's ok, we should keep it open so we remember how terrible the assertions are, and address when we feel like inflicting self-torture on ourselves :)

**Comment by IanEisenberg** [comment]
I'm closing this issue as it doesn't pertain to expfactory-experiments directly.
