### ISSUE TITLE
General issue about trial length and response deadline

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#106]
This first came up in simple RT but came up several times later. I think that in the absence of a compelling reason to do otherwise, we should trial lengths that are not determined by subject performance (i.e., either fixed at one duration or jittered, as in the simple RT task, but do not become shorter or longer based upon faster or slower responses). 

I think for some tasks (for example, stop-signal or go/no-go, but also many other tasks) it can be difficult to get a subject to balance the demands of speed and accuracy. By letting them complete the trials faster by responding faster (which is how I believe at least the simple & choice RT tasks are), I think this may shift the balance too far towards speed. If the trial lengths are all fixed, subjects cannot speed up the completion of the experiment by trading accuracy (or inhibition) for speed,  so they will instead just try to follow our instructions (to balance the competing demands of speed/accuracy/control)

**Comment by IanEisenberg** [comment]
This change has been implemented (though bugs may remain)
