### ISSUE TITLE
Simple RT 

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#107]
Related to (but somewhat distinct from) the general issue of performance-independent trial lengths, we should probably have something in the simple RT task that dissuades subjects from just pressing the spacebar constantly and not even attending to the task. Perhaps the best way would be to give them some form of negative feedback (e.g., "Please wait to respond until the stimulus appears) if they respond before the stimulus.

**Comment by jkl071** [comment]
For this issue, I could standardize trial length and make sure that the trial doesn't end when the subject makes a response to dissuade clicking through all the trials.  I could also add a fixed post_trial_gap.

**Comment by bissettp** [comment]
I would just have something long like a 1500ms display of the stimulus that also acts as the response window. But for the simple RT (because a viable strategy is to just pay no attention to the task but just keep pressing the necessary key) we should probably add some feedback for when they respond before the stimulus appears (see above)
