### ISSUE TITLE
Global Local 3

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#111]
![28](https://cloud.githubusercontent.com/assets/9681335/12826443/e0aeaa98-cb2f-11e5-953a-be864897b679.png)
<img width="1440" alt="28-2" src="https://cloud.githubusercontent.com/assets/9681335/12826448/e5dceb1a-cb2f-11e5-9283-52e66549bdda.png">

Stimuli in instructions were not being displayed

**Comment by vsoch** [comment]
This is 100% path error - the paths are specified relatively, and need to be specified globally. Eg:

      /static/experiments/local_global/images

and not

      static/experiments/local_global/images
