### ISSUE TITLE
General issue for questionnaires

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#113]
![14](https://cloud.githubusercontent.com/assets/9681335/12826564/70be8388-cb30-11e5-8d43-b5080fe91a54.png)
What is the purpose of the red stars? This is sometimes used in surveys when certain questions must be answered, but all questions must be answered so these stars seem unnecessary.

**Comment by zenkavi** [comment]
The red stars are indeed for required questions. I'm guessing you haven't tried to click next on any page where you haven't answered any of the stared questions? If you had it would not have allowed you to move forward and popped up a message. Though most people will assume that they should answer all questions some people forget or if they are going through it fast miss some of them so in general I include them as a reminder just in case. Also though for most questionnaires all questions are required there will be questions in the demographics that won't be so having this built-in the plugin structure keeps it more flexible. Let me know if this doesn't answer your concerns or feel free to close the issue if it does.

**Comment by bissettp** [comment]
sounds fine
