### ISSUE TITLE
Change Span to fixed trial length?

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#119]
There is an instruction that tells subjects that the task ends after 3 errors. For one, I think that we should remove the instruction that tells subjects about this. This may encourage subjects to do poorly to end the task more quickly. Also, why have this contingency in the task at all? Don't we want all subjects to experience the same number of trials even if they make 3 errors in a row?

**Comment by IanEisenberg** [comment]
I'm copying this: http://www.cambridgebrainsciences.com/browse/memory/test/digit-span

In addition, I believe the WAIS has an ending criteria of 2 misses. I agree that we shouldn't instruct them about this fact. The WAIS only increases, while we have it adapting (both up and down).
