### ISSUE TITLE
Impulsive venture 1 + others including mpq_control

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#121]
Instruction of "Do not think too long about the exact meaning" seems strange I would prefer it being omitted unless there is strong precedent in the literature for this exact instruction. We want them to understand the question and we want them to give their best answer. Of course we don't want them to sit and ponder for minutes, but the above instructions seems to encourage subjects to zip through without sufficient thought about the questions.

**Comment by zenkavi** [comment]
I agree with your concerns. This wording is taken from Eysenck et al.'s instructions for the I7 impulsiveness and venturesomeness subscales. So I suggest keeping the original wording for impulsive_venture. I removed it from instructions of mpq_control, for which I don't have the exact instructions in pr #217. Let me know if this is good to close this issue.

**Comment by bissettp** [comment]
I think we should discuss this tomorrow. There seem to be competing demands of: (1) having consistent instructions across questionnaires so that any results that we receive in a specific questionnaire isn't the result of some idiosyncrasy of the instructions (e.g., "do not think to long about the exact meaning") vs. (2) not diverging from the precedent set when the questionnaire was created/validated. As part of a large battery of many questionnaires, certain instructions being present in some but not other questionnaires  seems to implicitly suggest that the instructed strategy for responding should only be employed in that task and not others, which is probably not what we want. Let's discuss.

**Comment by zenkavi** [comment]
Valid concerns. Added to the agenda.

**Comment by IanEisenberg** [comment]
We have decided to keep these all consistent (by taking out any mention of speed/thinking for questionnaires). @zenkavi close this issue once that has been done.

**Comment by zenkavi** [comment]
To be discussed and resolved on 2/25 along with all other questionnaire instruction issues.
