### ISSUE TITLE
Spatial Span 1

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#124]
Had similar issues to digit span and could see the stim so couldn't evaluate the task. 
![27](https://cloud.githubusercontent.com/assets/9681335/12826929/3e042b8a-cb32-11e5-9da8-205ac92910ac.png)

**Comment by vsoch** [comment]
This looks like a chain of errors starting with the first line, "unexpected token else" I would first fix this issue, re-test the test, and if the stimulus is still not being displayed look for a path issue.

@bissettp your screenshots are excellent! So easy to debug stuffs :)
