### ISSUE TITLE
Go/no-go 2 + perhaps general issue about catch trials

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#126]
In the middle of the experiment I was presented with a Kerouac paragraph. I assume that this is some form of catch trial. This seemed like a bizarre form of catch trial, as it's a potentially interesting/emotional/bizarre diversion and task switch from what the subject is usually doing. I envisioned catch trials to be take minimal trials and be minimal engaging (e.g., "press T now if you're reading this prompt") in order to try to minimize the impact of catch trials on the task of interest.

**Comment by IanEisenberg** [comment]
Part of what I want to discuss on Thursday are catch trials. I originally had simple catch trials like you mentioned, but Zeynep mentioned that attention trials are normally more involved. Her lab used paragraphs with a lure. So at the bottom of the page it would say "Press A" but in the paragraph it would say "Press X" or "Press the title". I put in interesting paragraphs, but one might think that corrupts the data (while I thought it just made our subjects hate us a little less). We could put incredibly dry paragraphs about ...facts. I don't know - wiki articles.

**Comment by vsoch** [comment]
I've seen most of the catch trials, and I think they are exactly what we want - it's easy to read a line or two, but we really want to check if they are paying attention. If we have breaks between blocks, would it really impact the task? We could perhaps have somewhat simpler versions, but I think a nice meaty paragraph would be a good idea either toward the beginning or end, or at some kind of break.

**Comment by IanEisenberg** [comment]
I put them at the end of blocks to minimize immediate trial effects. It is true that someone may be thinking about the text rather than the experiment. We could just put one at the very end of the experiment, thus further minimizing effect (besides effecting the next task) but then it becomes difficult to reject. What is someone just screwed up on one?

**Comment by IanEisenberg** [comment]
In line with that, if we do go with the paragraph idea please send me paragraphs! Boring ones, informative ones, literature ones. Just give me paragraphs!

**Comment by vsoch** [comment]
If you want boring paragraphs, look no further than [GRE reading comprehension preparatory materials](http://www.majortests.com/gre/reading_comprehension.php)! I think I almost died taking that exam.
