### ISSUE TITLE
Columbia Card Hot 1

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#135]
Issues from Columbia Card Task (cold) are still here. Couldn't appropriately evaluate the task. 
![38](https://cloud.githubusercontent.com/assets/9681335/12827612/6803f188-cb35-11e5-982f-be06a0cd5ff3.png)

**Comment by jkl071** [comment]
There are some issues with display, but when playing the game play it in full screen mode.  When you have developer tools open it messes with the display.
