### ISSUE TITLE
Dot Pattern Expectancy 1

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#139]
![42](https://cloud.githubusercontent.com/assets/9681335/12827740/eee0a07a-cb35-11e5-8b97-dec55afbc3cb.png)
The stim in the instructions were not presented, so I didn't know the mapping. The stim in the main task were presented.

**Comment by jkl071** [comment]
This issue did not present for me, I also checked the paths of the stim but they seem to be correct.
