### ISSUE TITLE
Dot Pattern Expectancy 2

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#140]
I'm not sure if this resulted from me inputting "jspsych.finishTrial()" in the console, but the stimuli started being presented in extremely rapid succession (i.e., <100ms stimuli, trials with feedback only taking <500ms).

**Comment by jkl071** [comment]
I was able to recreate the error by inputting jsPsych.finishTrial().  However, since we are not supposed to do that, there's not much to do on the debugging side.  The cues are presented for 500ms, while the probes for 500ms with a response window of 1500ms.
