### ISSUE TITLE
Change Stim for different stop signal tasks

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#143]
How are we dealing with the response mapping given to an individual subject across the 3 different stop tasks? I think the best option is to give each subject the same go task mapping for each of the 3 tasks. If we switch mapping, I think we will get lots of errors and perhaps have to exclude lots of subjects (because of proactive interference of the previously learned response mapping in such a similar task).

**Comment by IanEisenberg** [comment]
We are not currently doing that nor is there an interface to even allow this. If you'd like we can use different shapes/keys across the three tasks.

**Comment by bissettp** [comment]
If possible, different shapes/keys for each of the stop tasks would be a great.

**Comment by IanEisenberg** [comment]
I think I'll use different stim and the same keys. Key overloading is inevitable across all tasks, and I doubt "M" vs. "Z" is as important as "left finger" vs. "right".

**Comment by bissettp** [comment]
Sounds reasonable
