### ISSUE TITLE
Kirby 1

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#152]
Instructions say subjects will be paid "proportional" according to one of the bets that they choose. How is this done? It is normal to be so vague about how the specifics of the payout?

**Comment by IanEisenberg** [comment]
see ART #154 . zenkavi says she put that as a placeholder, but I think we should be consistent about whether we explicitly mention bonuses or not. Let's discuss.

**Comment by bissettp** [comment]
I am fine with being consistently vague across tasks
