### ISSUE TITLE
mpq_control 1

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#153]
On the questionnaire page, I would display at the top of the screen the exact question that is being asked of each subject. What I mean is, currently it says, for example: "Stop one activity before completing it". This is presumably asking something like (I can't easily go back to the instrucs to I don't remember exactly): "Is it true or false that you generally...(then insert the statement for each true or false question". Maybe put this implicit first part of the question that is general for each question at the top of each sheet of the mpq_control

**Comment by zenkavi** [comment]
Pr #211 fixes this too.
