### ISSUE TITLE
MPQ control

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-experiments#159]
the "exp_id" must be the same as the folder name, MPQ_control != mpq_control:

https://github.com/expfactory/expfactory-experiments/blob/master/mpq_control/experiment.js#L32

This breaks export of results. I can "unbreak" by skipping export of these results, but then we are missing data.

**Comment by vsoch** [comment]
I'm going to see if I can make this test less conservative to catch this.

**Comment by zenkavi** [comment]
I think we should change all of them to be mpq_control instead of MPQ_control, including the directory name and all the exp_id variables. This will make it more consistent with the lack of capitalization in all other abbreviated questionnaire names. Will update this and send a pr.
