### ISSUE TITLE
ART 

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#162]
Instead of saying the number of red and the number or blue fish, it says red twice. 
![screen shot 2016-02-07 at 11 37 54 am](https://cloud.githubusercontent.com/assets/9681335/12874753/7129e180-cd8f-11e5-9a87-5285385bcfa2.png)

**Comment by vsoch** [comment]
Did you mean to close this?

**Comment by bissettp** [comment]
yes. It was a duplicate

On Sun, Feb 7, 2016 at 11:49 AM, Vanessa Sochat <notifications@github.com>
wrote:

> Did you mean to close this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-experiments/issues/162#issuecomment-181093712>
> .
>



-- 
Patrick G. Bissett
Postdoctoral Fellow
Stanford University
