### ISSUE TITLE
ART 3

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#164]
In doing the ART practice, I appeared to enter into an infinite loop in which if I pressed "Go Fish" I got: 

![screen shot 2016-02-07 at 11 45 59 am](https://cloud.githubusercontent.com/assets/9681335/12874801/65e9dd60-cd90-11e5-9a71-613d15b0e941.png)

And if I pressed "Collect" I got: 

![screen shot 2016-02-07 at 11 46 33 am](https://cloud.githubusercontent.com/assets/9681335/12874804/76908588-cd90-11e5-8ea7-a4a8b26aab00.png)

Because of this, I was unable to evaluate the rest of the task. This may have resulted from me only choosing 1 fish during the practice (when I am prompted to choose between 1-200 fish).

**Comment by vsoch** [comment]
I found this bug with the robot as well.

**Comment by IanEisenberg** [comment]
I am not sure if this is still an issue. I didn't have a clear separation from practice to test, so it may not have been an infinite loop, but a test loop. Either way, it has been made better and hopefully fixed.

**Comment by bissettp** [comment]
But don't you only choose your number of fish during practice? And if it's a test loop it presumably should not have always given me the blue fish when I chose "Go Fish".

**Comment by IanEisenberg** [comment]
I meant (which may not have been the case with you) that on the last
practice tournament you selected 1 fish and then it continued going round
after round through the test. Either way I've removed the one fish option -
not sure where the infinite loop would have come from.

On Monday, February 8, 2016, bissettp <notifications@github.com> wrote:

> But don't you only choose your number of fish during practice? And if it's
> a test loop it presumably should not have always given me the blue fish
> when I chose "Go Fish".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-experiments/issues/164#issuecomment-181612464>
> .
>


-- 
Best,
Ian
