### ISSUE TITLE
PRP 

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#165]
![screen shot 2016-02-07 at 11 49 03 am](https://cloud.githubusercontent.com/assets/9681335/12874829/e876de5e-cd90-11e5-81fa-95aa5071213c.png)

Something appears to be wrong with the display here. If I try to start the experiment the screen shows nothing. Couldn't evaluate the task.

**Comment by vsoch** [comment]
Javascript syntax error (unexpected token "else") is triggered, and that stops the experiment from running.
