### ISSUE TITLE
Directed Forgetting 2

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#168]
The forget cue wasn't displaying (the display went from the memory set of 6 immediately to the single probe letter)

**Comment by jkl071** [comment]
I did not see this issue. Did this happen for all trials?  Or did it start occurring in the middle of the experiment?  However, I do not think it is a problem with the experiment file itself, and seems to be more of a connection/timing problem. I am closing this issue.

**Comment by bissettp** [comment]
If I remember correctly, it was happening for all trials. I don't understand what you mean by a connection/timing issue or why this type of issue justifies disregarding and closing it.

**Comment by jkl071** [comment]
I do not have to close it, but the error is not displaying for me. I went through the entire experiment and only saw this on one trial, but on that trial, I was switching between tabs and the console was displaying error connection timeouts.  Because of this, I assumed that this error has more to do with connection/timing problems.

**Comment by vsoch** [comment]
@jkl071 you should never close an issue until the person opening the issue has communicated that they are satisfied with the resolution.

**Comment by jkl071** [comment]
Ok sounds good, I'll leave it open!

**Comment by bissettp** [comment]
I think it's fine to close an issue (without consulting me or whoever opened it) if it has been identified and definitively resolved. 

Jamie: What do you mean by a connection/timing problem and why does this type of problem not need to be kept open and solved?

**Comment by jkl071** [comment]
I thought it was a timing/connectivity issue because I went through the entire experiment and only saw this on one trial, but on that trial, I was switching between tabs and the console was displaying error connection timeouts.
