### ISSUE TITLE
Update cognitive reflection questions and specify how we want responses

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#171]
I think we need to tell subjects how we want them to respond. For example, in the first question (A bat and a ball cost $1.10 in total. The bat costs $1.00 more than the ball. How much does the ball cost?), should they say 5 cents, .05, $.05, 5c? Perhaps we need a bit of explanation, like "in cents" so they'd respond 5. 

Also, we need to either exclude this measure or ask Ellen Peters for her newer CRT questions. She said that most Turkers know the answer to these questions because they've seen them.

**Comment by IanEisenberg** [comment]
Yeah, this task needs to be update to new questions.

**Comment by IanEisenberg** [comment]
Questions added, but survey-text needs to be updated
