### ISSUE TITLE
Keep Track 1

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#172]
When you present the subjects with all of the members of each category in the instructions, it's unclear what the subject is supposed to do with this big block of examples. Are they supposed to remember them?

**Comment by bissettp** [comment]
What was the resolution for this?

**Comment by IanEisenberg** [comment]
I added this line before:
"To make sure there is no confusion about which word is in each category, the words in each category are presented below:"

and this line after: 
"Make sure you know which category each word belongs to."
