### ISSUE TITLE
Change Two Stage Decision instructions

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#180]
The instructions are extremely long. I think that we might be able to reduce text length and increase clarity by using more figures/graphics. For example, we might draw out the basic tree of 6 shapes and carry this tree forward throughout the instructions as a graphical representation of the task contingencies.

**Comment by IanEisenberg** [comment]
Yeah, I think this task can benefit from that. I'm not sure whether the original authors used a tree, but considering that we are explicitly telling them that one stage leads to another more often I think it's fine. It is the value-updating -> action transition we are interested in.

**Comment by IanEisenberg** [comment]
Instructions have been changed to include example trial. Still overly long and not close to what we want, but much better. I'm closing this issue as we have no plans to change them right now.
