### ISSUE TITLE
Self Regulation 2

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#182]
There appear to be 2 questions that are exact opposites: "I learn from my mistakes" and "I don't seem to learn from my mistakes". Could one of these questions possibly provide additional information once you've responded to the other? If these are in the questionnaire then I guess we should include it based on precedent, but this seemed pretty ridiculous.

**Comment by zenkavi** [comment]
I agree it is ridiculous but that is what's included in the original. If nothing else a negative correlation between these two can be an attention check.
