### ISSUE TITLE
Emotion Regulation 2

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#184]
(Copied from slack) 

I am running through the emotion regulation task right now. I agree with Ian that these are quite gruesome and unsettling. I think that these could: (1) significantly increase our attrition as some subjects will be unable/unwilling to continue the task given these images, and (2) influence performance on subsequent tasks by inducing a strong feeling/mood of disgust/sadness

I think that we should consider removing the task (and perhaps replacing it with an alternative measure of emotion regulation) or changing the images

**Comment by IanEisenberg** [comment]
I agree. We won't use it in the battery.
