### ISSUE TITLE
Implement image preloading

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#190]
On some of the trials, the 6 items in the memory set would appear at slightly different times from each other. It was not strikingly different nor consistent, but it was apparent enough to be distracting.

**Comment by jkl071** [comment]
When was this happening? Towards the end of the experiment or a random subset of trials?

**Comment by bissettp** [comment]
A random subset of trials. In this task (and most others), I only ran through a subset of the trials and did not make it to the end.

**Comment by IanEisenberg** [comment]
That has to do with image preloading, which we haven't dealt with yet and should.

**Comment by IanEisenberg** [comment]
It is a generic problem.

**Comment by IanEisenberg** [comment]
image preloading has been implemented on the tasks where it is most necessary. It should be implemented across the board eventually.
