### ISSUE TITLE
Recent Probes 2

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#191]
The duration that the memory set was on the screen seemed a bit too short to allow subjects to comfortably read and commit all 6 stimuli to memory. I would recommend increasing the duration of the memory set by 500ms.

**Comment by jkl071** [comment]
I can change that, I made it this way however because the task originally had this timing parameter.

**Comment by bissettp** [comment]
When you say "the task originally" had this timing parameter, what paper are you citing?

**Comment by jkl071** [comment]
Hi Patrick,

I cited the paper associated with recent probes/directed forgetting in the
google docs.
Here is the link: http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2206737/

Best,
Jamie
