### ISSUE TITLE
holt_laury 1

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#192]
Each choice was similarly close to it's horizontal pair (the one that I think you're supposed to compare it to) as it's closest vertical neighbor. To make it more clear that the comparison is to be made between each stimulus and its horizontal pair, we should increase the vertical distance between each pair of choices.

**Comment by zenkavi** [comment]
There is currently a star indicating the required questions and separating the questions. The horizontal distance is already smaller than the vertical. Also traditionally these gambles are often presented without any vertical space (see http://users.nber.org/~rosenbla/econ311-04/syllabus/holtlaury.pdf). I see why you might be potentially confused though so I suggest updating the instruction to read "Please indicate your preference between each of the pairs of gambles." Do you think this would help?

**Comment by bissettp** [comment]
yes

**Comment by zenkavi** [comment]
Ok. This is now done in pr #215. Do you have any other comments for holt and laury or is it good?
