### ISSUE TITLE
hierarchical_rule 1

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#197]
When I started (and presumably the instructions should have been presented), nothing happened:

![screen shot 2016-02-08 at 2 42 35 pm](https://cloud.githubusercontent.com/assets/9681335/12901793/639806da-ce72-11e5-8c26-232eb646041f.png)

 When I clicked the spacebar I saw a "next" box, so i clicked it and got the following:

![screen shot 2016-02-08 at 2 44 12 pm](https://cloud.githubusercontent.com/assets/9681335/12901805/70c93b26-ce72-11e5-9d3c-4bb9d7a29659.png)

Without the instructions, I didn't know how to respond when stimuli started being presented.

**Comment by IanEisenberg** [comment]
The background should have been black. Was the background black for this, the dietary decision task or the PRP task?

**Comment by bissettp** [comment]
I don't remember
