### ISSUE TITLE
stop_signal 1

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#199]
I would make the stop stimulus black instead of red. There is some research suggesting that stimuli with natural associations with inhibition (e.g., red -> stop sign -> stopping) influence/speed inhibition. I don't think that we want to wade into that literature without stop task.

**Comment by IanEisenberg** [comment]
Should everything be black then? What about the stimulus specific stop? I could make the stop signal purple, and for the stimulus-selective, orange and blue (which I am currently using)

**Comment by bissettp** [comment]
Stimulus selective stop needs to be a color (because that's the dimension that they are selecting on), and orange and blue are fine. I don't know what you mean by "everything" but I think the stop stimuli and go stimuli should be black for the stop signal and motor selective stopping paradigm. The go stim should be black for stim selective stop and only the stop stimuli should have a color in stim selective stop

**Comment by IanEisenberg** [comment]
I meant that both the stim and stop-signal would be black. Sure, I can do that.
