### ISSUE TITLE
"poldrack-single-stim" == issues with the signals , and suggestions for the instruction 

### ISSUE THREAD

**Issue by tnsgmddb** [expfactory/expfactory-experiments#229]
![3_wrong signals](https://cloud.githubusercontent.com/assets/16784562/13056164/9f086a9c-d3e1-11e5-981b-113b14348a47.png)

 trial_type: "poldrack-single-stim",  

In the Practice trials:  I didn't see any of the shapes "square , circle, triangle, or diamond." 
Only "+" appeared throughout a few rounds of practice trials. 

After a few sets of practice trials, I started seeing only the Square shape a few times within each trial, but I don't see other shapes.
 
============================================response order and use of pictures 

The current order of responses shown on the screen  is: 
    Square: Z key
    Circle: M key
    Triangle: Z key
    Diamond: M key 

Consider organizing the order as follows: 
     Square: Z key
    Triangle: Z key
    Circle: M key
    Diamond: M key 

In the instruction, it will be good to use an actual picture of the shape a participant will see , instead "word (e..g, square)"

**Comment by IanEisenberg** [comment]
I think this is the stop-signal task. When you say "poldrack-single-stim" you are reporting the trial_type. That shouldn't come up where I told you to look in the original email. If it does, please show me a screen shot. I'll look into this error.

**Comment by IanEisenberg** [comment]
I fixed the images I have not done anything to the instructions. We have many tasks where instructions could be improved and I don't believe the stop signal is too bad right now, especially considering the fact that the practice repeats and progresses in stages to allow people to 'get it'. I agree in principle that images would be preferable to words, but I am not going to make these changes now. Let me know if you feel strongly about this!

**Comment by tnsgmddb** [comment]
Ok, sure! 
I don't have strong preference about using images for the instructions.
