### ISSUE TITLE
exp_id: "leisure_time_activity" = Font size for "response texts"  a bit too small. 

### ISSUE THREAD

**Issue by tnsgmddb** [expfactory/expfactory-experiments#230]
Object { view_history: "[{"page_index":0,"viewing_time":712…", rt: 71241, exp_id: "leisure_time_activity", trial_type: "poldrack-survey-multi-choice", trial_index: 2, time_elapsed: 78246, internal_node_id: "0.0-2.0" }

Consider to make it bigger.

**Comment by IanEisenberg** [comment]
Done
