### ISSUE TITLE
 Nogo with orange or blue squres  == details for instruction 

### ISSUE THREAD

**Issue by tnsgmddb** [expfactory/expfactory-experiments#232]
If you see the orange square you should respond. If you see the blue square you should not respond. Press enter to begin.

Respond means pressing any key on the keyword ? if so, consider to state "Press any key on your keyboard"

**Comment by IanEisenberg** [comment]
Considering the point about the spacebar was in the last paragraph, I didn't add it again. I did move everything to one page so it is easier to see that though.
