### ISSUE TITLE
'exp_id': 'digit_span'  practice vs actual tasks?

### ISSUE THREAD

**Issue by tnsgmddb** [expfactory/expfactory-experiments#233]
'exp_id': 'digit_span'
I took the practice trial, then the experiment asked me to type shown numbers in a reverse order. 
I thought this "reverse" task was still part of the practice session. But this reverse task ended and the screen says "experiment Complete" 

Not clear if "typing numbers in reverse order was the actual task, or I didn't get the actual task at all. 

ALso, if this task is purely based on memorizing, you may add statements like : 
"please do not write down the numbers. Take this task based on your memory. If is OK to get the answers wrong. We just want to understand how people memorize numbers"

**Comment by IanEisenberg** [comment]
What practice trial? And type digits? Did your digit span not have a numpad? "Practice" should not be listed anywhere. 

What do you think of this change of instructions?

"In this test you will have to try to remember a sequence of numbers that will appear on the screen one after the other. At the end of each trial, enter all the numbers into the presented numpad in the sequence in which they occurred. Do your best to memorize the numbersd, but do not write them down or use any other external tool to help you remember them

**Comment by IanEisenberg** [comment]
If this change seems suitable, could you close this issue? If not, please let me know what else I should do.

**Comment by tnsgmddb** [comment]
The revised instruction sounds good.

**Comment by tnsgmddb** [comment]
What practice trial? 
-->  Before the actual trials started, I was asked to practice first , and after each practice trial I got "correct" or "incorrect" feedback on my response. I received feedback on each practice trial. 
Then, I expected the actual trials would begin after these practice trials, but the experiment ended. So I am not sure if I supposed to have actual trials after those practice trials. 
==================================

Did your digit span not have a numpad?
-->  Sorry about the confusion. I did use the numpad.

**Comment by IanEisenberg** [comment]
There are no practice trials and you shouldn't have been asked to practice first...not sure what's going on there but it is certainly on longer doing that.
