### ISSUE TITLE
 'exp_id': 'go_nogo'  : incorrect feedback; instruction; neutral priming 

### ISSUE THREAD

**Issue by tnsgmddb** [expfactory/expfactory-experiments#234]
### In the practice trial, I followed the instruction, But the feedback doesn't seem right. 
e.g., I purposely responded incorrectly, but I get "correct" as feedback.  
=======================================

The instruction of this task was , 
"We will now begin the first test block. You will no longer get feedback about your responses.
If you see the orange square you should not respond. If you see the blue square you should respond. Press enter to begin." 
==> like the Nogo task, you may add how participants should respond. As a participant taking this task for the first time, I was not sure how I suppose to respond. It can be pressing any button on keyboard, or clicking my mouse.  So please consider adding more specific instruction. e.g., "press the space bar on your keyboard" 
========================

In a few cases during the actual trials,  I see an orange square for a very short time (like 200 ms) then it changed to blue square without any neutral priming screen (the white blank screen). Is this the right design of this task? Or there should have been a blank screen between the orange and blue squares?

**Comment by IanEisenberg** [comment]
I fixed the instructions to be in line with the practice instructions (so it says "by pressing spacebar".)

I am getting correct feedback during practice and I don't see the blue -> orange switch. Did you happen to enter "jsPsych.finishTrial()" before this?

**Comment by tnsgmddb** [comment]
hmm. .. in the previous task, I entered that a few times, but not in the right before this task.  
Whenever I enter that function, I get "TypeError: timeline[current_location] is undefined" anyways.
