### ISSUE TITLE
IE - Next page button issues

### ISSUE THREAD

**Issue by magvt** [expfactory/expfactory-experiments#235]
1) I haven't kept track but it seems that this has happened with most of the instruments: when I click 'next' within an instrument, I'm sent to the bottom of the next page and I need to scroll up to the top.  
2) the next button often appears in the middle of the screen - see the following examples:
![dospert_rt_next](https://cloud.githubusercontent.com/assets/17258830/13059633/a0a920ae-d3f9-11e5-82fb-831e6cd6e3d3.jpg)
![dosbert_eb_next](https://cloud.githubusercontent.com/assets/17258830/13059639/a667bba4-d3f9-11e5-9ea2-67fb2cb86e95.jpg)
![brief_self_control_next](https://cloud.githubusercontent.com/assets/17258830/13059646/ade73562-d3f9-11e5-9c25-9832680564f8.jpg)
3) The next button didn't work in the dickman or brief self control instrument.

**Comment by IanEisenberg** [comment]
I am not seeing this error using Edge on Windows or chrome on windows/linux. What IE version are you using?

The reason the next button isn't working in (3) is probably because it is beneath other content.

**Comment by magvt** [comment]
IE 11.

**Comment by zenkavi** [comment]
Ah! I'm sorry I should have kept it all on this one but opened another general issue on the same thing so I'm closing this now..
