### ISSUE TITLE
Angling task amounts

### ISSUE THREAD

**Issue by magvt** [expfactory/expfactory-experiments#236]
Odd amounts showing up in the Tournament Bank - I've attached some screen shots:
![angling_bankamt](https://cloud.githubusercontent.com/assets/17258830/13059744/614875a8-d3fa-11e5-9620-89b5bb9fac34.jpg)
![angling_bankamt2](https://cloud.githubusercontent.com/assets/17258830/13059746/6252a504-d3fa-11e5-82cb-a55d5e51f932.jpg)
Other examples of amounts that showed up: 3.5999..., 10.7999..., 20.15000...2, 33.800...4, 5.94999..., 13.049..., 13.8999..., 14.249....   That list is not exhaustive.

**Comment by IanEisenberg** [comment]
Ugh, these are supposed to round. I don't know why they don't sometimes. Hmm

**Comment by magvt** [comment]
I tried to figure out a pattern but couldn’t.  It happened maybe 25% of the time.

**Comment by IanEisenberg** [comment]
Well, I changed how pay is displayed. Hopefully it will now work better...

**Comment by magvt** [comment]
Thanks.  Do you want me to try it again?
Also – when I refresh the page I’m sent to tasks I’ve already done.  Does this me I’m done?  Are there others you’d like me to test?
