### ISSUE TITLE
Infomration sampling task

### ISSUE THREAD

**Issue by magvt** [expfactory/expfactory-experiments#237]
1) I had to scroll down each time to see the last row.  
2) The colors of the large box sometimes bled into the smaller boxes.  
![info sampling_lost choice](https://cloud.githubusercontent.com/assets/17258830/13059864/35fc4770-d3fb-11e5-84e3-594ce11b541a.png)
![info sampling_lost choice2](https://cloud.githubusercontent.com/assets/17258830/13059865/384dfdca-d3fb-11e5-91d5-72bd4c0cec9a.jpg)

**Comment by IanEisenberg** [comment]
These have been fixed.
