### ISSUE TITLE
Spatial span

### ISSUE THREAD

**Issue by magvt** [expfactory/expfactory-experiments#239]
Twice it said 4 squares but only showed 3.  Or I only saw 3.  Could've been me - but it happened twice,  once in the reverse set.

**Comment by IanEisenberg** [comment]
I don't think that could happen (which is my way of saying - I have no idea why that bug would be there and don't know how to address it). However, it is possible that the same item came up twice in a row which you didn't see. I changed the task so the same item can't come up twice in a row (same for digit span, so no sequences like: 6, 4, 4, 5, 3..."

**Comment by tnsgmddb** [comment]
@IanEisenberg , 
In the trial, (I think it was a third trial), it says 4 Squares in text but only three squares changed to red.

In the reverse order trials, 5 squares in text but only 3 squares changed to red. 

Attaching screenshots where I think related to those error spots. 
![17_spatial span](https://cloud.githubusercontent.com/assets/16784562/13194067/facb2e54-d752-11e5-9160-b310a4f23c75.png)
![17_spatial span_reverse](https://cloud.githubusercontent.com/assets/16784562/13194066/facadb98-d752-11e5-991a-4e71ac9eb13e.png)
