### ISSUE TITLE
'exp_id': 'psychological_refractory_period'

### ISSUE THREAD

**Issue by tnsgmddb** [expfactory/expfactory-experiments#243]
The consent form and instructions showed in font color = white. 
![1_consent-font color](https://cloud.githubusercontent.com/assets/16784562/13062394/6f5e9660-d40c-11e5-9657-2b2095968692.png)
![1_intructions-color](https://cloud.githubusercontent.com/assets/16784562/13062395/6f690226-d40c-11e5-9aac-b9df68119362.png)

=========
The instructions page changed to black, and the overlapped texts made it hard to understand the guidelines.Even the wording of the instructions was not clear.  I was not sure what I needed to do in this task. 

![4_psychological_refractory_period_instct](https://cloud.githubusercontent.com/assets/16784562/13062433/a5444590-d40c-11e5-8be9-bbf13b03fddb.png)
![4_psychological_refractory_period_instct0](https://cloud.githubusercontent.com/assets/16784562/13062434/a546b0be-d40c-11e5-96d6-fbdf1a239a1b.png)

==================== The background color in this task changed between blue and black  back and forth.  
![4_psychological_refractory_period](https://cloud.githubusercontent.com/assets/16784562/13062480/09c83c7e-d40d-11e5-8783-3e8617348c39.png)
![4_psychological_refractory_period_background](https://cloud.githubusercontent.com/assets/16784562/13062481/09c8a7b8-d40d-11e5-8cff-ca8c44ef22d3.png)
![4_psychological_refractory_period_color](https://cloud.githubusercontent.com/assets/16784562/13062482/09cba328-d40d-11e5-89f9-8a5dcbda1d3e.png)

**Comment by IanEisenberg** [comment]
No idea where that blue comes from...but it's a nice color. I've fixed the consent. Will work on the overlapping text.

One point - when your console is open, the screen will be squashed. We have tested the experiments on a number of screen sizes/aspect ratios, but the "squareish" aspect ratio that gets created when you have the console open is not something we are currently planning on accounting for. That may explain why there is overlapping text/boxes. If you see things like this in the future, see if the experiment looks screwed up without the console open.
