### ISSUE TITLE
'exp_id': 'attention_network_task'--display issue; response time recorded correctly?

### ISSUE THREAD

**Issue by tnsgmddb** [expfactory/expfactory-experiments#245]
Just FYI, I have the task window open on my laptop screen. Without the console window opening on the side, the arrows are still not located properly.  I see arrows appearing all the way bottom, and they are cut out.  When I moved the window to the external large screen, I see arrows without being cut.  So people using a small screen device may encounter this issue. 
 
![5_network task](https://cloud.githubusercontent.com/assets/16784562/13063087/7e8a8882-d412-11e5-98dc-e15e85f4486e.png)

-------------
More importantly, I see each stimulus content (a set of 5 arrows) is designed to show up on the screen until I respond or for 2000 milliseconds at the longest . I expect that the screen goes to the next stimulus content once I enter my responses (either <- or ->).  But it seems the screen changed after 2 seconds , rather than immediately after my response was entered.  So if my response latency was 500 milliseconds for one stimulus content, I expect to see the next stimulus content immediately, but I have to wait for 1500 milliseconds. 
I wonder if my response latency has been recorded correctly.

**Comment by tnsgmddb** [comment]
2 suggestions: 
1) I think it will reduce study attrition if you inform participants upfront how many trials they will be asked in the actual task. You may consider including this info briefly in the instructions. 

2) It seems the number of trials in this task is 300 or more? (omg) It feels really long for one task. I wonder if it is a threat to internal validity if you reduce the number of trials to less than 100.

**Comment by IanEisenberg** [comment]
Yeah, the number of trials...hmm. This is one of those super tasks - it combines flanker with an alerting spatial cue. There are 4 types of cues, 2 locations, 2 arrow directions and 3 conditions (congruent/incongruent/neutral). So we have 48 individual stimuli and repeat them all 6 times... Whether this is necessary I'm not sure, but we have a number of tasks that are of this kind - the shift task, the 3by2, angling risk task. These are tasks that measure many things - I don't think we want to reduce them.

Progress bars may help, but I worry about the effect or progress bars. We'll think on this more. @bissettp, @poldrack what are your thoughts?

**Comment by poldrack** [comment]
I think that 6 trials per cell is probably as low as we want to go.  
I don’t feel strongly about progress bars

**Comment by IanEisenberg** [comment]
If we were to reduce, we would have to decide (now) that we would collapse across something - probably arrow direction (left vs. right) as the original authors found no difference between those two (they collapsed across them). We could then reduce the experiment length.

**Comment by poldrack** [comment]
that seems fair, no reason to think that arrow direction should be an important effect relevant to self-regulation

**Comment by bissettp** [comment]
I also think that arrow direction is a reasonable thing to collapse across. 

However, I'm less clear why 300 trials for a single task is problematic (other than the obvious desire to keep the battery from becoming extremely long). Compared to how these cognitive tasks are often ran in the lab (i.e., for an hour with >1000 trials), our tasks are quite short.  Most of our tasks are shorter than 300 trials, but a small number of them are approximately this length. For these complicated designs (e.g., 4x2x3), ~300 trials seemed like a reasonable compromise between a reasonable number of trials per cell (in this case, 12, even if we collapse across location) and not being too long/boring.

**Comment by IanEisenberg** [comment]
The original task was developed to be fairly efficient. A selling point was "only 30 minutes!" But I think we should keep in mind that people in general don't like doing a cognitive task for a long time. This is more practicality - if there is fat we can cut, we should cut it.

**Comment by vsoch** [comment]
I want to +1 shortening some of the tasks.

Also, small screens should not be an issue, the application does not allow experiments to be taken on mobile devices.
