### ISSUE TITLE
adaptive n-back 

### ISSUE THREAD

**Issue by magvt** [expfactory/expfactory-experiments#247]
When I was slow to respond - hitting the space bar just after the letter was off the page, it was unclear to me if a new set of letters was appearing or not.  Can you set timing a little longer between sets or somehow indicate when a new set appears?

Also a typo in the following (lsat instead of last)
![nback paragraph typo](https://cloud.githubusercontent.com/assets/17258830/13080260/e2819690-d495-11e5-959a-273ab1cdc25e.jpg)

**Comment by IanEisenberg** [comment]
I'm a bit unclear about what you mean by "new set of letters". A new letter appears regardless of what you do every 2s.

What happens right now (and I think this is confusing so I may remove - let me know your thoughts) is after you respond the letter turns red. If you respond after the letter is on the screen however (during the delay between letters) your response is still valid - there jsut is no cue to show you. I'm thinking of remove the cue altogether.

**Comment by magvt** [comment]
Actually, I'm not sure what I meant either!  I can go back to it later, or tmr.  Sorry.
