### ISSUE TITLE
two-stage decision

### ISSUE THREAD

**Issue by magvt** [expfactory/expfactory-experiments#248]
I can't access this - I get a blank screen.

**Comment by IanEisenberg** [comment]
Did your web console say anything? Report any errors?

**Comment by magvt** [comment]
Sorry – I mistakenly opened this in firefox and got a blank screen – I’ve attached a screen shot of the web console. Hope that helps.
It seems fine in IE.

**Comment by magvt** [comment]
In IE, the following issues:
1) Nit-picky.  Instructions read "after you press 'next'..." but there is no next button.
![two stage instructions](https://cloud.githubusercontent.com/assets/17258830/13086865/2751daec-d4b3-11e5-81c8-1683ec9fd198.jpg)
2) Images are not appearing on each screen.
![two stage image](https://cloud.githubusercontent.com/assets/17258830/13086887/3ebe31b2-d4b3-11e5-96ce-34566bd84f01.png)
3) Just stopped working. blank screen.
![two stage sto ped](https://cloud.githubusercontent.com/assets/17258830/13087343/61ebc1e8-d4b5-11e5-8821-e2b45ef5e558.jpg)

**Comment by IanEisenberg** [comment]
I imagine you closed this issue by mistake. Let me know if all these problems magically fixed themselves :)

**Comment by magvt** [comment]
Yes, closed by mistake.  Sorry!

**Comment by IanEisenberg** [comment]
We have addressed this issue. Small bug where firefox doesn't like stimulus: "". It wants " ". Also fixed missing image.
