### ISSUE TITLE
motor selective stop icon

### ISSUE THREAD

**Issue by magvt** [expfactory/expfactory-experiments#249]
I'm just seeing + (plus signs).
![motor selective](https://cloud.githubusercontent.com/assets/17258830/13083438/feafd7c0-d4a2-11e5-8e27-4c9f79f02f8b.jpg)

**Comment by IanEisenberg** [comment]
This is the same issue as #229 and should have been resolved.

**Comment by magvt** [comment]
Same issue with stop_signal.
![stop signal](https://cloud.githubusercontent.com/assets/17258830/13096651/0342f5f6-d4e9-11e5-8b3b-d4b86b2e3294.jpg)

**Comment by tnsgmddb** [comment]
I got this task again. And I only see plus signs (+), but based on @IanEisenberg 's response 
 here, I assume this issue has been resolved.
