### ISSUE TITLE
directed forgetting

### ISSUE THREAD

**Issue by magvt** [expfactory/expfactory-experiments#251]
I went through a *lot* of screens,  then a screen appeared saying that the test would begin. (That screen also has a typo):
![directed forgetting typo](https://cloud.githubusercontent.com/assets/17258830/13087912/fd428e68-d4b7-11e5-9097-095eaf27e462.png)
Prior to that screen, the pace was very slow but after that screen, it was way too fast - I couldn't even process them.  Plus I never got to any instructions about only remembering the top or bottom letters.

**Comment by IanEisenberg** [comment]
Not sure about the speed changes, but I reduced the number of screens and the typo has been fixed
