### ISSUE TITLE
kirby delay discounting

### ISSUE THREAD

**Issue by magvt** [expfactory/expfactory-experiments#253]
Q and P keys don't do anything.  Also tried left, right arrows but they didn't work.
![kirby](https://cloud.githubusercontent.com/assets/17258830/13088618/f2c61cf4-d4ba-11e5-8103-7393e26ef65b.jpg)

**Comment by zenkavi** [comment]
Could you check if there are any errors in your javascript console? Were you able to complete the task in another way?

**Comment by magvt** [comment]
Sure – but I need 5 minutes to create an issue for PRP.

**Comment by magvt** [comment]
Here's the console code:
![kirby console](https://cloud.githubusercontent.com/assets/17258830/13096502/db43b33e-d4e7-11e5-92bd-3ec5e510b6db.jpg)

**Comment by magvt** [comment]
OK,I added a comment.  Does this help to print the screen?
Do you want me to continue testing other instruments, or respond to questions now?  Happy to do either/both.

**Comment by jkl071** [comment]
Hi, I ran into a similar issue with discount titrate.  Zeynep, I can fix this if you haven't yet. It's just the response_ends_trial parameter.

**Comment by zenkavi** [comment]
Go for it Jamie i'm working on the surveys. Thanks!
