### ISSUE TITLE
local global

### ISSUE THREAD

**Issue by magvt** [expfactory/expfactory-experiments#254]
Two issues:
After *many* screens, then the screen appears that says now we'll start the test.  (That language is confusing to me - is it the test or the real thing?)
Then, after that screen - I couldn't progress.  
![local global stuck](https://cloud.githubusercontent.com/assets/17258830/13089133/406e4394-d4bd-11e5-8c0c-ab2d48901824.jpg)

**Comment by IanEisenberg** [comment]
Fixed the progression problem. Not sure what you mean about all of the screens - there is a "We are starting practice" and a "we are staring test", so hopefully that's clear.

**Comment by magvt** [comment]
Do all the experiments and questionnaires use practice and test consistently?  For some reason, I think I was interpreting test as test-run.  Maybe define the terms (for dolts like me), or use another word for test?
