### ISSUE TITLE
Recent probes

### ISSUE THREAD

**Issue by magvt** [expfactory/expfactory-experiments#261]
A*lot*of practice tests before the task.  Also, the wording is confusing about when the actual task begins and the test ends because after the tests, a screen appears saying we'll begin with tests.   At the end, just a blank screen, no indication that it was over.

**Comment by IanEisenberg** [comment]
I have fixed some things about recent probes. There are only 4 practice trials and there is an end message, so again...unfortunately not sure what's going on. We want to make this work with IE, but not a priority.
