### ISSUE TITLE
impulsive_venture

### ISSUE THREAD

**Issue by magvt** [expfactory/expfactory-experiments#262]
1) the response buttons are really small.  I didn't think I skipped any (but may have because of the size of the buttons).  Is it possible that when that error msg appears about missing responses that it resets other responses to missing?  Either that I I missed a lot.  
2) Next button appears in middle of page; I needed to scroll back up to progress.
3 )Next button goes to bottom of next page.
4) typo: "wish" doesn't need capitalization.
![impulsive_ventrue](https://cloud.githubusercontent.com/assets/17258830/13118129/cc206134-d570-11e5-95ef-66e07eeaeb30.jpg)
5)

**Comment by zenkavi** [comment]
1. next button definitely doesn't reset the entered responses if any are skipped but i do see the point on small radio buttons. i opened a general issue about this so this is no longer specific to this questionnaire.

2. next button in the middle of the page: general issue, not specific to this questionnaire

3. fixed where next button lead to in pr 39 to expfactory-battery

4. fixed typo in pr 292
