### ISSUE TITLE
MPQ wording

### ISSUE THREAD

**Issue by magvt** [expfactory/expfactory-experiments#263]
1) Next button placement in middle of page, and sends to bottom of next screen.
2) Wording is sometimes odd.  The prompt: "is it true or false that you generally..." and responses: Fast and careless.  I am methodical. Have a good idea of what I'm going to do.   Doesn't flow.   
3) I think the word "keep" is missing from "close track of money."
![mpq wording](https://cloud.githubusercontent.com/assets/17258830/13118533/9531afe6-d572-11e5-872d-04000a585d87.jpg)

**Comment by magvt** [comment]
Also - what's potholing?

**Comment by zenkavi** [comment]
I think my understanding of the wording of the items was incorrect for this questionnaires. So I changed all items to be full sentences (e.g. replaced "cautious person" with "I am cautious person"). 

re potholing: we had no idea either and you are 2/2 out of testers asking this. We could consider removing this item but that would sway a litthe away from the original. @bissettp @IanEisenberg what do you think?

**Comment by zenkavi** [comment]
Closing this issue since mpq issues are resolved and "potholing" is part of another questionnaire (impulsive_venture) that we are discussing separately.
