### ISSUE TITLE
SSS

### ISSUE THREAD

**Issue by magvt** [expfactory/expfactory-experiments#264]
1) Next button - same issues (middle of screen, sends to bottom of next screen).
2) Typo in hypnotized
![sss](https://cloud.githubusercontent.com/assets/17258830/13118873/51795a18-d574-11e5-9bc4-18561002e44b.jpg)
3) response buttons really small.

**Comment by zenkavi** [comment]
Fixed typo in pr #290 and the other issues are not specific to this questionnaire but have separate general issues so closing this issue.
