### ISSUE TITLE
exp_id: "self_regulation" - Next and Previous buttons not working.

### ISSUE THREAD

**Issue by tnsgmddb** [expfactory/expfactory-experiments#267]
![6_self-reg](https://cloud.githubusercontent.com/assets/16784562/13121254/9d515b42-d57f-11e5-9912-9212699c3f02.png)

## **I pressed the Next button, then I get this error message. **
TypeError: trial.pages[current_page] is undefined
check_required_questions()
 jspsych-poldrack-survey-multi-choice.js:259
next()
 jspsych-poldrack-survey-multi-choice.js:212
show_current_page/<()
 jspsych-poldrack-survey-multi-choice.js:197
m.event.dispatch()
 jquery.min.js:4
m.event.add/r.handle()
 jquery.min.js:4

**When I press "Previous" I get this error:**
TypeError: trial.pages[current_page] is undefined
update_page_data()
 jspsych-poldrack-survey-multi-choice.js:285
back()
 jspsych-poldrack-survey-multi-choice.js:376
show_current_page/<()
 jspsych-poldrack-survey-multi-choice.js:190
m.event.dispatch()
 jquery.min.js:4
m.event.add/r.handle()
 jquery.min.js:4

**Comment by zenkavi** [comment]
Fixed in pr #296
