### ISSUE TITLE
emotion regulation

### ISSUE THREAD

**Issue by magvt** [expfactory/expfactory-experiments#270]
Technical issues first:
1) No navigation buttons.
2) Slow to load - may have been because of no navigation buttons.
3) Some gruesome photos, then "Now we'll start some practice."  
4) In the actual test, photos and prompts came too quickly, seemed to overlap.

I couldn't even look at some of these photos. Really gruesome.

**Comment by magvt** [comment]
I couldn't finish the questionnaire because of speed of screens, which was a relief, actually, because of the content.

**Comment by IanEisenberg** [comment]
We are removing this task from the battery, but good to know about the errors.

**Comment by IanEisenberg** [comment]
Not sure what the timing issues or navigation button issues are, but the task is working fine on my end. Maybe this is another IE bug, which we don't have time to eal with unfortunately. Implemented image preloading which should smooth out the task overall and cleared up instruction.
