### ISSUE TITLE
"writing_task"

### ISSUE THREAD

**Issue by tnsgmddb** [expfactory/expfactory-experiments#271]
I had to be on the page longer than 10 minutes, like for 13 minutes or so.  
There was no button to go to the next step, It'd be useful to have a NEXT button on the bottom inactive until 10 minutes elapse then become active after 10 minutes elapse. 
 Also can you change the duration (10 minutes) shorter if that doesn't interfere with the purpose of this task?

**Comment by IanEisenberg** [comment]
10 minutes is arbitrary, but the idea of the task is to provide us with a (potentially) rich data source that can be mined for useful features. One feature may actually be length of writing, so we will get more variance if we allow a longer time (some will give up/run out of things to say earlier).

I'll look into the timing issue.

**Comment by tnsgmddb** [comment]
As a participant, I had to admit that I was bored and almost got some negative affect toward the task b/c there was no control over going to the next button unless I exit the page by refreshing it. 
To make the experience more engaging you may provide more control for the participants (e.g., provide them with a next button so that they have control over proceeding after "X" minutes elapse. For the "X" minutes, I don't know what'd be the optimal duration, although personally I felt 10 minutes were too long).

**Comment by IanEisenberg** [comment]
I'll lower it to 5 minutes
