### ISSUE TITLE
"columbia_card_task" - pics and texts overlap

### ISSUE THREAD

**Issue by tnsgmddb** [expfactory/expfactory-experiments#273]
The pictures and texts look like this. 
![7_columbia_](https://cloud.githubusercontent.com/assets/16784562/13124557/0e64844e-d58f-11e5-9300-195174892e8a.png)  
![7_columbia_2](https://cloud.githubusercontent.com/assets/16784562/13124685/94715648-d58f-11e5-9084-4b6f7ae14f05.png)

I minimized the screen size, no overlap but texts were too small to read. 
![7_columbia_3](https://cloud.githubusercontent.com/assets/16784562/13124659/7579f164-d58f-11e5-8b89-555a68879b2c.png)

**Comment by tnsgmddb** [comment]
![7_columbia_4](https://cloud.githubusercontent.com/assets/16784562/13162194/2a3eda9c-d671-11e5-99ef-2a0b077633e1.png)

I got this task at random and yesterday these cards were clickable. But today when I clicked these cards,  nothing happened. So I am stuck on the very first page. Exiting the task by closing the window (FireFox).

**Comment by IanEisenberg** [comment]
We are working on the CCT. It has been remade so this issue is no longer relevant.
