### ISSUE TITLE
"local_global"  The same exp_ID as #274 but this was a different task; I'm stuck in the first page of the actual trial; adding the response options.

### ISSUE THREAD

**Issue by tnsgmddb** [expfactory/expfactory-experiments#277]
![12_local global](https://cloud.githubusercontent.com/assets/16784562/13129834/919c8e2e-d5ad-11e5-848c-04c4ba8aab81.png)
I pressed 1,2, and 3 one at a time but not moving to the next page. 

Also it d be very important to have the response options on the side of the screen throughout,  so that people know what number key to enter. I forgot what number was for what shape. I may have a lot of incorrect responses not because I was a scam but because I just don't remember the response options.

**Comment by IanEisenberg** [comment]
We are changing this task to the original Navon task, where the stimuli are "H"'s and "S"'s. You respond by pressing "H" and "S", so much easier to remember. The stuck issues have been dealt with locally, but haven't yet pushed to expfactory.org
