### ISSUE TITLE
exp_id Raven == response options identical ? 

### ISSUE THREAD

**Issue by tnsgmddb** [expfactory/expfactory-experiments#278]
![11_raven](https://cloud.githubusercontent.com/assets/16784562/13129928/64f8d2be-d5ae-11e5-98d7-1b8b3b84a587.png)

This trial seems to be based on jpg files, but I noticed the response options (E) and (F) the same?

**Comment by zenkavi** [comment]
Pr #280 fixes this. Thanks for catching.
