### ISSUE TITLE
shift task

### ISSUE THREAD

**Issue by magvt** [expfactory/expfactory-experiments#282]
I get just a blank screen.
![shift task blank screen](https://cloud.githubusercontent.com/assets/17258830/13151279/7def2082-d637-11e5-96f1-a71aaf820c57.jpg)

**Comment by IanEisenberg** [comment]
When you post a console image - please paste the "console" tab, not the debugger so I can see what errors show up.

**Comment by magvt** [comment]
Sorry.  Would you like me to go back and get the console image?

**Comment by IanEisenberg** [comment]
No, I'll take care of it. Thanks!

**Comment by magvt** [comment]
Sorry about that.  I’m done for this round – except for the Barratt, I think I’ve done everything.
Let me know if there’s anything else.
Thanks.
mag
