### ISSUE TITLE
hierarchical_rule ====present the response options, j, k, and l

### ISSUE THREAD

**Issue by tnsgmddb** [expfactory/expfactory-experiments#295]
Presentation ]
It'd be useful and important to present the response options on the side so that 
people know when to click j, k, or l. 
![13_hierarchical_rule](https://cloud.githubusercontent.com/assets/16784562/13162676/5206cb72-d674-11e5-8e49-e382d238e03a.png)

**Comment by IanEisenberg** [comment]
This wasn't done in the original study and isn't done in any other task. I'm going to assume they can remember the three keys.

**Comment by tnsgmddb** [comment]
Ok.Sure.Not this task, but in general cognitive tasks that display response options (visually) seem pretty common. But I think for a series of cognitive tasks within one study (like ours), there should be consistency throughout tasks (all having response options displayed or not at all for all tasks). I recall that most of our tasks don't have responses options. 
Also, if remembering the response options throughout the task is also part of measuring cognitive capacity, then not displaying response options makes sense.  
====
on another note, for data from cognitive tasks, reaction times with incorrect responses will be separately analyzed (or excluded) from those reaction times with correct answers, I guess?  Some papers report the percentage of inaccurate responses out of the total responses first, then they do not include reaction times with incorrect responses for main analyses. I'm sure you may already know there are large literature about reporting latency responses for cognitive tasks. Too soon for now, but look forward to hearing about your plans/strategies for analyzing latency responses.
