### ISSUE TITLE
choice_reaction_time== stuck in the 1st page 

### ISSUE THREAD

**Issue by tnsgmddb** [expfactory/expfactory-experiments#299]
The interface is stuck on the first page.
![14_choice reactiontime1](https://cloud.githubusercontent.com/assets/16784562/13192814/0660eb10-d73e-11e5-8329-f7695011b3b6.png)

 I looked up the page source to get the exp_id; It says 
![14_choice reactiontime](https://cloud.githubusercontent.com/assets/16784562/13192787/d46dc894-d73d-11e5-908e-e8b27d9f9127.png)

But when I checked the choice_reaction_time demo on "https://expfactory.github.io/table.html" , this task I am stuck is not choice_reaction_time. It's something else.

**Comment by IanEisenberg** [comment]
This should be fixed.
