### ISSUE TITLE
questionnaire options text wrapping

### ISSUE THREAD

**Issue by zenkavi** [expfactory/expfactory-experiments#300]
fix css to have options wrapping around flex box if font is made larger

**Comment by zenkavi** [comment]
Work around listed here https://github.com/philipwalton/flexbugs#2-column-flex-items-set-to-align-itemscenter-overflow-their-container for issue 2 might be helpful.
(Also related to now close issues 283, and 284 for lcat and eating questionnaire)

**Comment by vsoch** [comment]
closing since moved to expfactory-surveys
