### ISSUE TITLE
attention checks for questionnaires

### ISSUE THREAD

**Issue by zenkavi** [expfactory/expfactory-experiments#301]
add function to check rt for each page of questionnaire after submitting

**Comment by zenkavi** [comment]
@IanEisenberg when you get a chance can you point me to an example for this in the task and i'll modify and add to questionnaires

**Comment by IanEisenberg** [comment]
if you check the simple reaction time you can see an "assessPerformance" function. I'll have to add an experiment variable to the config file for it to be usable. I haven't done that yet so maybe hold off worry about that particular issue.

**Comment by zenkavi** [comment]
not implementing for now. will re-open later if necessary
