### ISSUE TITLE
shift_task=== blank after first response

### ISSUE THREAD

**Issue by tnsgmddb** [expfactory/expfactory-experiments#302]
I didn’t understand what I need to do in the actual task after reading the instruction, “We will now start the test. You will no longer be told what the important feature is or when it switches. Press enter to begin.”  

And after my reaction to the 1st trial of the actual test, the screen goes to blank.
![19_shift_task](https://cloud.githubusercontent.com/assets/16784562/13194369/c5c6a2a0-d75d-11e5-9c3d-d28b8a61e693.png)

**Comment by IanEisenberg** [comment]
I believe this is fixed.
