### ISSUE TITLE
directed_forgetting -- blank page

### ISSUE THREAD

**Issue by tnsgmddb** [expfactory/expfactory-experiments#303]
I finished the first round of tests. 
And I saw the instruction second time, “ We will now start a test run. Remeber, at the end of the trial respond with the Left arrow key if the letter presented is in the memory set, and the Right arrow key if it is not in the memory set.” 

then the next page goes blank. 
![20_directed_forgetting_blank](https://cloud.githubusercontent.com/assets/16784562/13194482/8a014d2a-d761-11e5-9b12-363f94cdd1d1.png)

ps- I was confused alter and forgot  the instruction about which key was for what. It can be easy to forget if a person is taking this task in a casual setting like listening to music. Anyways, it can be just me.

**Comment by IanEisenberg** [comment]
This should be fixed.
