### ISSUE TITLE
dietary_decision ==== consent form and blank page

### ISSUE THREAD

**Issue by tnsgmddb** [expfactory/expfactory-experiments#304]
The consent form in this task was written in black and white so it looked like this: 
![1_consent-font color_strange](https://cloud.githubusercontent.com/assets/16784562/13194520/b4377154-d762-11e5-8844-f2444f790649.png)

The 3rd set of trials asking if I will eat the food or not went "blank page' after the instruction.  
![21dietary_decision](https://cloud.githubusercontent.com/assets/16784562/13194528/db121dec-d762-11e5-98c0-4aaf940af7c8.png)

**Comment by IanEisenberg** [comment]
There were many issues with the dietary task that I thought I had taken care of, but didn't commit (evidently). They should be fixed now.
