### ISSUE TITLE
go_nogo == nothing happened after the instruction page

### ISSUE THREAD

**Issue by tnsgmddb** [expfactory/expfactory-experiments#308]
After the responses options (below) were provided, stimulus words do not show up on the first page of the trial. And no page progress either, I was just stuck on the first page. 
I see three words on the bottom of the first page, but nothing happened. There was no input area to type/enter words. 

•	animals: fish, bird, snake, cow, whale
•	colors: red, yellow, green, blue, brown
•	countries: China, US, England, India, Brazil
•	distances: mile, kilometer, meter, foot, inch
•	metals: iron, copper, aluminum, lead, brass
•	relatives: mother, father, brother, sister, aunt

**Comment by IanEisenberg** [comment]
I'm not getting this error on firefox or chrome on Linux. I'll have to test on Windows.
