### ISSUE TITLE
experiments using jquery should be updated to use jquery in static/js/jquery folder

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-experiments#310]

**Comment by IanEisenberg** [comment]
In comparison to what? What are they currently using? The Jquery they are using is referenced by the template exp.html

**Comment by vsoch** [comment]
where is [this one](https://github.com/expfactory/expfactory-battery/blob/master/static/js/jquery-1.11.2.min.js) used?

**Comment by IanEisenberg** [comment]
That one is never used. We also have jquery in static/lib, which seems to be the one used by the [exp.html template: ](https://github.com/IanEisenberg/expfactory-battery/blob/master/templates/exp.html)

The template files just need to be changed and we need to remove useless jquery. the lib folder is maybe necessary for psiturk.

**Comment by IanEisenberg** [comment]
How do you want us to proceed here? We should probably keep our version of jquery in static/lib to stay consistent with psiturk's suggestion: http://psiturk.readthedocs.org/en/latest/file_desc/static_lib_folder.html

We currently do that, so we should get rid of all other jqueries (like the one in static/js and static/js/jquery)

**Comment by vsoch** [comment]
Agreed, let's keep as is for now.
