### ISSUE TITLE
FYI: list of experiment js errors

### ISSUE THREAD

**Issue by jkredz** [expfactory/expfactory-experiments#322]
Came across some js errors while testing experiments from https://expfactory.github.io/table.html and generating batteries from expfactory.

**Digit Span** - Clear button doesn't clear entries
**Flanker** - After the first test, the following error occurs "Failed to load resource: the server responded with a status of 404 (NOT FOUND) experiment.js:257 Uncaught TypeError: jsPsych.addDataToLastTrial is not a function"
**n-back** - When starting the experiment: Uncaught TypeError: DOM_target.addClass is not a function experiment.js:257

Also the plus-minus experiment seems to only output the values that the user enters.  But I didnt see any parameters (correct/incorrect output or correct answer output) to compare with the user entries in the csv result file.

**Comment by vsoch** [comment]
These are great! Thanks for finding these - we are still actively developing the tasks and @IanEisenberg and @zenkavi are hard at work fixing these bugs.

**Comment by jkredz** [comment]
No problem!  Just wanted to give you guys a heads up.
Thanks for your hard work in putting together this open source platform.

**Comment by vsoch** [comment]
our pleasure! :)

**Comment by IanEisenberg** [comment]
These errors have been fixed and will be merged shortly. Thanks for finding them!

**Comment by vsoch** [comment]
@IanEisenberg why did you re-open?

**Comment by IanEisenberg** [comment]
I hadn't actually merged when I closed, so wanted to wait until I merged the fix, but then didn't close the issue. Please close it.

**Comment by vsoch** [comment]
Great, thanks!
