### ISSUE TITLE
Demographics Potential Bug

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-experiments#388]
For this question:

      On average, how many cigarettes do you now smoke a day (1 pack = 20 cigarettes)?

It is fourth in the list, so it corresponds to opts_8 here:

      [opts_5, opts_6, opts_7, opts_8, opts_9, opts_18]

and that makes sense, opts_8 is as follows:

      var opts_8 = ["Less than a cigarette a day", "<5", "5-10", "10-20", "1 pack", "2 packs", "More than 2 packs"]
      var scale_8 = {"Less than a cigarette a day": 1, "<5":2, "5-10":3, "10-20":4, "1 pack":5, "2 packs":6, "More than 2 packs":7}

but the question itself is indicated to be "number" when it should be radio (fourth one again):

      ["radio", "radio", "radio", "number", "radio", "checkbox"]

**Comment by zenkavi** [comment]
Yes, I just didn't remove this after adding the functionality to include number input boxes. Should not break the task. Just messy code. It serves as a place holder in the other arrays (for options and scoring objects for each question not throw off the loops later) so I left it

**Comment by vsoch** [comment]
ok, it definitely just threw me off... someone else looking at the code would conclude there is a bug or the options are incorrect.

**Comment by zenkavi** [comment]
completely agree. all the more reason to move to your new architecture. i haven't been particularly incentivized to create the cleanest code i possibly could especially given the time constraints and my limited skilset

**Comment by vsoch** [comment]
moved to expfactory-surveys
