### ISSUE TITLE
Demographics: Smoking

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-experiments#389]
I might be missing some conditional functionality built into a plugin, but it looks like the user is required to answer question about smoking, and there is no obvious "I don't smoke" response.

**Comment by zenkavi** [comment]
The questions are not required. It would be nicer of course if there was a conditional function where the smoking questions didn't even appear for those who don't smoke at all but I haven't coded that yet

**Comment by vsoch** [comment]
moved to expfactory-surveys
