### ISSUE TITLE
Demographics: First Questions

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-experiments#390]
The first string of questions that ask about numbers of things (eg, children, married) are specified as number, but they also have choices. It's not clear to me if this is to be a numeric field, or a radio field to choose the number?

**Comment by vsoch** [comment]
Take a look at the options for these questions - for example, how tall are you in inches, and how much do you weigh, is given options on a scale of 0 to 5 - it could be that specifying these as numeric means they aren't used at all (and extra data in the array?) but on the other hand, the field specified as numeric that asks about number of children should probably use the opts_10 to control what the user can specify.

**Comment by zenkavi** [comment]
see response to issue #388 for this. if they are specified as number in the input array then the input will be number box but for scoring loops in the plugin a place holder is required in the options and scoring object arrays so i left them there which were from an earlier version of the plugin that didn't have different input options

**Comment by vsoch** [comment]
moved to expfactory-surveys
