### ISSUE TITLE
Are dospert_rp and dospert_rt supposed to be different?

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-experiments#394]
I just want to confirm - these are the exact same questions, but one asks about risk, and the other asks the participant how likely he/she is to do something?

dospert_rt:

![image](https://cloud.githubusercontent.com/assets/814322/13650366/2b897c1e-e5f7-11e5-9dec-99f6afd0eece.png)

dospert_rp:

![image](https://cloud.githubusercontent.com/assets/814322/13650375/443876ac-e5f7-11e5-9b8d-6d2cdb31f7d1.png)

**Comment by IanEisenberg** [comment]
@zenkavi, can you confirm?

**Comment by zenkavi** [comment]
Yes, they're different though the scenarios are the same

**Comment by vsoch** [comment]
Thanks for clarifying! Yeah I realized after the fact that the questions are the same, but response options are different. Makes sense!
