### ISSUE TITLE
impulsive_venture scoring scale is backwards

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-experiments#398]
Here

https://github.com/expfactory/expfactory-experiments/blob/master/impulsive_venture/experiment.js#L94

The array for "score_scale" needs to have the index at 0 switched with the index at 1, as the first set of questions is N=15, and the second is N=19, and the scoring has [19,15]

**Comment by zenkavi** [comment]
Thanks for catching this. Added the three missing items to the first page in pr #404 to expfactory-experiments.

**Comment by vsoch** [comment]
moved to expfactory-surveys
