### ISSUE TITLE
exp_id is not being exported with results

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-experiments#405]
true for "perceptual_metacognition" as well as "probabilistic_selection" - likely others as well.

**Comment by IanEisenberg** [comment]
Yeah, not sure what's going on. I'll look into this.

**Comment by IanEisenberg** [comment]
This is likely do to on_finish (the function that calls add_ID()) being overwritten on many blocks when it is defined within the experiment.js folder. Will check.

**Comment by IanEisenberg** [comment]
@vsoch, I believe I've identified the problem and it is more problematic than I realized.

Below I've pasted the jspsch.init from an experiment, bolding two relevant functions:

******************************

jsPsych.init({
timeline: threebytwo_experiment,
display_element: "getDisplayElement",
fullscreen: true,

**on_trial_finish**: function(data){
addID()
},
**on_data_update**: function(data){
expfactory.recordTrialData(data);

expfactory.djstatus = "UPDATE";
$.ajax({ type: "POST",
contentType: "application/json",
url : "/local/776/",
data : JSON.stringify(expfactory),
dataType: "json",
success: function(data){
console.log("data update called")
}
});

******************************

"on_data_update" gets called when the plugin calls a "write" method on that trial. _then_ on_trial_finish gets called, which append exp_id to the previous trial. So it goes like....

Trial 1 generates some data (key press)
on_data_update gets called
on_trial_finish gets called, which appends data to the just created data object (but expfactory never sees it).

Trial 2 generates some data (key press)...


******************************

One fix is to just move all the "on_data_update" functionality to "on_trial_finish". However, there are times when I use jsPsych's "addDataToLastTrial" method, which does exactly as the name suggests. So Trial 2 in the above example could write to trial 1.

To deal with those two issues, we could move data updating to on_trial_finish and resave the last N trials (where N is the largest amount we can save quickly and easily - 2 may be sufficient, I'd have to think) each time.

**Comment by vsoch** [comment]
Don't forget that you have total programatic control to these functions in the config.json, the reason addID is there is because that's where you put it, eg:

https://github.com/expfactory/expfactory-experiments/blob/master/angling_risk_task/config.json#L44

**Comment by IanEisenberg** [comment]
addID is in the correct spot. This is a larger issue, as I tried to explain.

expfactory.recordTrialData(data); is called on every "data_update". However, that trial's data may change after expfactory.recordTrialData(data); is called, either because of a function called in "on_trial_finish" or because of a subsequent trial changing its data.

For example, by the end of a sequence of trials jsPsych's data may end up being:
data = [trial_id: press_button, key_press: 70, correct: true], [trial_id: feedback]
generated like so:
Trial 1 -> [trial_id: press_button, key_press: 70]
Trial 2 -> [trial_id: feedback] -> call addDataToLastTrial({correct: true})

That sequence of trials generates the above data list, but trial 1's data is partially created by trial 2.
Expfactory saves Trial 1 immediately after trial 1, and thus would save:
[trial_id: press_button, key_press: 70], [trial_id: feedback],
missing the "correct" attribute

**Comment by vsoch** [comment]
The entire data is saved each time, so whatever updates were done to the data after the first trial will be saved when the function calls to save data 2.

**Comment by vsoch** [comment]
This is not a problem with expfactory, it's an issue related to jspsych. The expfactory js is just an array of data that holds things when they are sent. If there is an issue with timing it needs to be resolved by changing the jspsych init. If it's a larger issue with JsPsych you should talk to Josh. I'm not sure what you are asking me to do about this.

**Comment by IanEisenberg** [comment]
This is not a jspsych problem. If I preview a task on expfactory.org - the data object itself is correct, however the data is not being saved to expfactory correctly. It is not being saved in exactly the way I mentioned - expfactory is recording data once and not resaving the data after it is updated. I have sent a PR to update the test task so I can show you more explicitly what I mean.

**Comment by vsoch** [comment]
Then why don't you compare the preview init with the version expfactory generates, and determine what needs to be done to save the data? Showing me a difference between data files doesn't help anything. I'm not saying the problem doesn't exist, I'm saying you should proactively determine how to fix it.

**Comment by vsoch** [comment]
For example, if saving the data on_data_update isn't the right time to save it... what about saving it at... another time? :P

**Comment by vsoch** [comment]
Give a go at setting up the test environment we talked about, let me know how it goes, or if you have questions about what to try next.

**Comment by vsoch** [comment]
@IanEisenberg if you want to test and confirm that with the recent fix https://github.com/expfactory/expfactory-python/commit/d56d6d79121e42716b25198d7395b9fbfcfce7b5 the addID() function is working to add the exp_id, we can close this issue.

**Comment by IanEisenberg** [comment]
Tested - looks good. We can close.

**Comment by vsoch** [comment]
Excellent.
