### ISSUE TITLE
Adaptive_n_back updating load

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-experiments#412]
Right now load is being increased almost every block because of an issue with update_load. 

Also, right now each trial just randomly draws a letter. Probably should change it so that there is a constant probability of drawing a target letter (or a constant number of targets across the block). @poldrack and @bissettp, do you have any input on this? (The likelihood of a "go" trial in the n_back experiment)

**Comment by IanEisenberg** [comment]
I'm adapting from [this paper](http://www.pnas.org/content/105/19/6829.full), where they had 33% of trials = target trials, so I'm going to do that.

**Comment by bissettp** [comment]
I like having the exact same number of trials of interest for each subject (as opposed to a complete randomization of trials), and I often ensure that this is the case within each experimental block. T
