### ISSUE TITLE
number_Letter display issue

### ISSUE THREAD

**Issue by tmaldonado1821** [expfactory/expfactory-experiments#498]
The number_letter task stops displaying stimuli about halfway through the experiment. I am able to see stimuli rotate between the top left and right quadrant and then switch to alternating between the bottom left and right quadrant. I believe once the task is to switch to show stimuli randomly across all 4 quadrants, the display issue occurs. When the stimuli are no longer presented, I am still able to press "Z" and "M" and those responses are recorded, however, there are no stimuli to respond to.

**Comment by vsoch** [comment]
@IanEisenberg @zenkavi @jkl071 has anyone looked into this issue?

**Comment by IanEisenberg** [comment]
Sorry on the delay here! That task was not completed to work with the current version of experiment factory. I'll take a look at it and try and get it working by the end of the weekend.

**Comment by vsoch** [comment]
Awesome! Thanks @IanEisenberg

**Comment by vsoch** [comment]
@tmaldonado1821, @IanEisenberg has updated the experiment, and I've deployed it for your preview here:

http://expfactory.github.io/number_letter.html

Could you test and see if the issue is fixed to your liking?

**Comment by tmaldonado1821** [comment]
@vsoch and @IanEisenberg , this preview works great! Thanks so much for fixing this issue. It is greatly appreciated!

**Comment by vsoch** [comment]
np! Thanks for bringing it to our attention.
