### ISSUE TITLE
Robot to run tasks

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-experiments#51]
Given that we are just using jspych right now, I see no reason that I can't make some kind of robot that can read the task structure, and push the required button to go through the tasks. This will be step 1, and step 2 will be to integrate tests into that process so all experiments can be automatically tested for errors.

**Comment by vsoch** [comment]
Robot is done, both for local and CI use.

**Comment by jodeleeuw** [comment]
This is something I want to implement for jspsych, which currently has no testing whatsoever. I'd be really grateful for any help you could offer along these lines.

**Comment by vsoch** [comment]
the robot is mostly finished... give it a go! install [expfactory-python](https://github.com/expfactory/expfactory-python) and then the command is:

      expfactory --test

It just works with firefox for now, and not yet all tasks, mainly just because I'm adding functionality as I see bugs.

**Comment by vsoch** [comment]
I'd definitely be happy to help with something for jspsych in isolation of experiment factory. Testing JavaScript is hard, for sure. The next few months are going to be a bit nuts, but I'll have some time after that :)

**Comment by jodeleeuw** [comment]
Great! It'll be a huge help.
