### ISSUE TITLE
Favicon.ico

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-experiments#58]
As a part of #57 some script is trying to load a "favicon.ico" at the server base `/favicon.ico` I can't seem to find this in any of the direct css files, so likely it is hiding with the other bug. This also needs to be resolved as it will fail tests.

**Comment by IanEisenberg** [comment]
Have we resolved this? I still see it but can't find it either

**Comment by vsoch** [comment]
Nope. The only way I resolved this in testing was to add a favicon.ico to the generated folder of experiments that are tested. I still have no idea where this sneaky thing is coming in!

I'll take a look now. It's either hidden somewhere in a style file, or in jspsych.

**Comment by vsoch** [comment]
It's a browser default, i did grep over all battery files and didn't see it either

![image](https://cloud.githubusercontent.com/assets/814322/12995294/440064be-d0db-11e5-9d8a-df332b10dcb0.png)

**Comment by vsoch** [comment]
It's dealt with for the tests, so it's not an issue. I'm going to close this.
