### ISSUE TITLE
"Dospert" experiments need better documentation

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-experiments#6]

**Comment by zenkavi** [comment]
@vsoch could you be more specific?

**Comment by vsoch** [comment]
This was an issue done a long time ago, but I think it was referring to the fact that we didn't have references and details about the dospert experiments in the cognitive atlas.

**Comment by vsoch** [comment]
Given the amount of work on your plate, it would be ok to close this issue, but at some point we need to describe experiments fully in Cognitive Atlas.

**Comment by zenkavi** [comment]
Yes, there are a bunch of experiments that we just created tags for and they all need to be described in further detail at some point. Shall we close this issue here then and perhaps @jkl071 can go through all our tasks in cog at and make sure they are described?

**Comment by vsoch** [comment]
+1
