### ISSUE TITLE
Questionnaire instructions pressing ENTER doesn't work

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-experiments#93]
The instructions tell the participant to press enter, but it doesn't actually work (End instructions does). This is for dospert_rt, so I'm guessing it is a bug in the other tasks as well.

**Comment by zenkavi** [comment]
This was leftover from changing survey instructions plugins from jspsych-instructions to poldrack-instructions. Thanks for catching it. I think pr # 218 should have fixed this.
