### ISSUE TITLE
Initial battery Instruction feedback:1

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#99]
It says something like subjects should pay attention "Because we have hidden tasks in these blocks". Though that's true, that's not why subjects should pay attention. They should pay attention because this is what we are asking them (and they are agreeing) to do. Perhaps delete.

**Comment by IanEisenberg** [comment]
what is this in response to? What text?

**Comment by bissettp** [comment]
The link that Vanessa sent me had some initial instructions before entering any specific task. This is in response to those instructions.
